class ItemsOperators:
  bl_idname = "object.animation_effects"
  bl_label = "Animation Effects"
  items = [
    ('WAVE', "Wave Motion", "Apply a wave effect"),
    ('BOUNCE', "Bounce Motion", "Apply a bounce effect"),
    ('SHAKE', "Shake Motion", "Apply a shake effect"),
    ('SPIN', "Spin Motion", "Apply a spin effect"),
    ('FADE', "Fade Motion", "Apply a fade effect"),
    ('BLINK', "Blink Motion", "Apply a blink effect"),
    ('ZOOM', "Zoom Motion", "Apply a zoom effect"),
    ('ROTATE', "Dynamic Rotate", "Apply a rotation effect"),
    ('SQUASH_STRETCH', "Squash & Stretch Motion", "Apply a squash and stretch effect"),
    ('WIGGLE', "Wiggle Motion", "Apply a wiggle effect"),
    ('TWIST', "Twist Motion", "Apply a twist effect"),
    ('SINE_WAVE', "Sine Wave Motion", "Apply a sine wave effect"),
    ('BOUNCE_BACK', "Bounce Back", "Apply a bounce back effect"),
    ('JELLY', "Jelly Motion", "Apply a jelly effect"),
    ('FOLLOW_PATH', "Follow Path", "Make the object follow a path"),
    ('FOLLOW_OBJECT', "Follow Object", "Make the object follow another object"),
    ('SPRING', "Spring Rigid", "Apply a spring effect"),
    ('PULSE', "Pulse Motion", "Apply a pulse effect"),
    ('CLOTH', "Cloth Simulation", "Simulate a cloth effect"),
    ('VORTEX', "Vortex Simulation", "Simulate a vortex effect"),
    ('RIGID_BODY', "Rigid Body Simulation", "Apply rigid body physics"),
    ('SOFT_BODY', "Soft Body Simulation", "Apply soft body physics"),
    ('FLUID', "Fluid Simulation", "Simulate fluid dynamics"),
    ('RAIN', "Rain Particles", "Create a rain particle effect"),
    ('SNOW', "Snow Particles", "Create a snow particle effect"),
    ('SPARKLES', "Sparkles Particles", "Create sparkles particle effect"),
    ('FIREWORKS', "Fireworks Particles", "Create fireworks particle effect"),
    ('EXPLOSION', "Explosion Particles", "Create explosion particle effect"),
    ('SMOKE', "Smoke Particles", "Create smoke particle effect"),
    ('LEAVES', "Leaves Particles", "Create falling leaves particle effect"),
    ('BUBBLES', "Bubbles Particles", "Create bubbles particle effect"),
    ('CONFETTI', "Confetti Particles", "Create confetti particle effect"),
    ('FIRE', "Fire Particles", "Create fire particle effect"),
    ('PLASMA', "Plasma Particles", "Create plasma particle effect"),
    ('SPARKS', "Sparks Particles", "Create sparks particle effect"),
    ('RAINBOW', "Rainbow Particles", "Create rainbow particle effect"),
    ('LIGHTNING', "Lightning Particles", "Create lightning particle effect"),
    ('DUST', "Dust Particles", "Create dust particle effect"),
    ('ASH', "Ash Particles", "Create ash particle effect"),
    ('GLITTER', "Glitter Particles", "Create glitter particle effect"),
    ('FROST', "Frost Particles", "Create frost particle effect"),
    ('BLOOD', "Blood Particles", "Create blood particle effect"),
    ('SPIDER_WEB', "Spider Web Particles", "Create spider web particle effect"),
    ('GHOST', "Ghost Particles", "Create ghost particle effect"),
    ('MIST', "Mist Particles", "Create mist particle effect"),
    ('GLITCH', "Glitch Effect", "Apply a glitch effect"),
    ('PIXELATE', "Pixelate Effect", "Apply a pixelate effect"),
    ('BLUR', "Blur Effect", "Apply a blur effect"),
    ('SHARPEN', "Sharpen Effect", "Apply a sharpen effect"),
    ('COLORIZE', "Colorize Effect", "Apply a colorize effect"),
    ('BLACK_WHITE', "Black & White Effect", "Apply a black and white effect"),
    ('SEPIA', "Sepia Effect", "Apply a sepia effect"),
    ('VIGNETTE', "Vignette Effect", "Apply a vignette effect"),
    ('LENS_FLARE', "Lens Flare Effect", "Apply a lens flare effect"),
    ('BLOOM', "Bloom Effect", "Apply a bloom effect"),
    ('CHROMATIC_ABERRATION', "Chromatic Aberration", "Apply a chromatic aberration effect"),
    ('NOISE', "Noise Effect", "Apply a noise effect"),
    ('GRAIN', "Film Grain Effect", "Apply a film grain effect"),
    ('LENS_DISTORTION', "Lens Distortion", "Apply a lens distortion effect"),
    ('HOLOGRAM', "Hologram Effect", "Apply a hologram effect"),
    ('GLOW', "Glow Effect", "Apply a glow effect"),
    ('REFLECTION', "Reflection Effect", "Apply a reflection effect"),
    ('SHADOW', "Shadow Effect", "Apply a shadow effect"),
    ('LIGHT_RAYS', "Light Rays Effect", "Apply light rays effect"),
    ('FISHEYE', "Fisheye Effect", "Apply a fisheye effect"),
    ('KIRBY', "Kirby Effect", "Apply a Kirby effect"),
    ('PIXEL_SORT', "Pixel Sort Effect", "Apply a pixel sort effect"),
    ('WIRE', "Wireframe Effect", "Apply a wireframe effect"),
    ('FLASH', "Flash Effect", "Apply a flash effect"),
    ('SPOTLIGHT', "Spotlight Effect", "Apply a spotlight effect"),
    ('NEON', "Neon Effect", "Apply a neon effect"),
    ('GLOWING', "Glowing Effect", "Apply a glowing effect"),
    ('FIREWORKS_LIGHT', "Fireworks Light", "Apply fireworks light effect"),
    ('LENS_FLARE_LIGHT', "Lens Flare Light", "Apply lens flare light effect"),
    ('RAY_TRACING', "Ray Tracing", "Apply ray tracing effect"),
    ('SHADOWS', "Dynamic Shadows", "Apply dynamic shadows effect"),
    ('GLOBAL_ILLUMINATION', "Global Illumination", "Apply global illumination effect"),
    ('MATERIAL', "Material Effect", "Apply a material effect"),
    ('TEXTURE', "Texture Effect", "Apply a texture effect"),
    ('NORMAL_MAP', "Normal Map Effect", "Apply a normal map effect"),
    ('DISPLACEMENT', "Displacement Effect", "Apply a displacement effect"),
    ('REFRACTION', "Refraction Effect", "Apply a refraction effect"),
    ('EMISSION', "Emission Effect", "Apply an emission effect"),
    ('TRANSLUCENT', "Translucent Effect", "Apply a translucent effect"),
    ('SUBSURFACE', "Subsurface Scattering", "Apply subsurface scattering effect"),
    ('ANISOTROPIC', "Anisotropic Effect", "Apply an anisotropic effect"),
    ('TRANSPARENT', "Transparent Effect", "Apply a transparent effect"),
    ('GLOSSY', "Glossy Effect", "Apply a glossy effect"),
    ('MATTE', "Matte Effect", "Apply a matte effect"),
    ('METALLIC', "Metallic Effect", "Apply a metallic effect"),
    ('PLASTIC', "Plastic Effect", "Apply a plastic effect"),
    ('WOOD', "Wood Effect", "Apply a wood effect"),
    ('STONE', "Stone Effect", "Apply a stone effect"),
    ('CARPAINT', "Car Paint Effect", "Apply a car paint effect"),
    ('GLASS', "Glass Effect", "Apply a glass effect"),
    ('ICE', "Ice Effect", "Apply an ice effect"),
    ('PATH', "Camera Path", "Create a camera path effect"),
    ('TRACK', "Camera Track", "Track the camera to an object"),
    ('FOCUS', "Camera Focus", "Set camera focus on an object"),
    ('DEPTH_OF_FIELD', "Depth of Field", "Apply depth of field effect"),
    ('LENS_DISTORTION_CAMERA', "Lens Distortion Camera", "Apply lens distortion to camera"),
    ('CAMERA_SHAKE', "Camera Shake", "Apply camera shake effect"),
    ('CAMERA_ZOOM', "Camera Zoom", "Apply camera zoom effect"),
    ('CAMERA_ROTATE', "Camera Rotate", "Apply camera rotation effect"),
    ('CAMERA_FOLLOW', "Camera Follow", "Make the camera follow an object"),
    ('CAMERA_PAN', "Camera Pan", "Apply camera panning effect"),
    ('CAMERA_TILT', "Camera Tilt", "Apply camera tilting effect"),
    ('CAMERA_DOLLY', "Camera Dolly", "Apply camera dolly effect"),
    ('CAMERA_TRACKING', "Camera Tracking", "Track the camera to a moving object"),
    ('CAMERA_STABILIZATION', "Camera Stabilization", "Stabilize the camera movement"),
    ('CAMERA_FOCUS_PULL', "Focus Pull", "Pull focus during camera movement"),
    ('CAMERA_LENS_FLARE', "Lens Flare", "Add lens flare effect to camera"),
    ('TIME_WARP', "Time Warp", "Apply a time warp effect"),
    ('SLOW_MOTION', "Slow Motion", "Apply a slow motion effect"),
    ('FAST_FORWARD', "Fast Forward", "Apply a fast forward effect"),
    ('REVERSE', "Reverse", "Apply a reverse effect"),
    ('FREEZE_FRAME', "Freeze Frame", "Apply a freeze frame effect"),
    ('CINEMATIC', "Cinematic", "Apply a cinematic effect"),
  ]
